# UScan releases

'*anongit.neon*':
  '{Neon/release,Neon/release-lts}':
    upstream_scm:
      type: uscan

'*anonscm.debian*':
  '*':
    upstream_scm:
      type: uscan

'ubuntu':
  '*':
    upstream_scm:
      type: dsc

'*github.com*':
  '*':
    upstream_scm:

# Plasma

'*{anonscm.debian,anongit.neon}*/plasma/*':
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: Plasma/5.9

'*{anonscm.debian,anongit.neon}*/plasma/plasma-discover':
  '*':
    upstream_scm:
      url: git://anongit.kde.org/discover.git

'*{anonscm.debian,anongit.neon}*/plasma/plasma-mediacenter':
  '*':
    upstream_scm:
      branch: Plasma/5.7

# Calligra

'*{anonscm.debian,anongit.neon}*/calligra/calligra*':
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: master

'*{anonscm.debian,anongit.neon}*/calligra/{kdb,kreport,kproperty,kexi}*':
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: 3.0

'*{anonscm.debian,anongit.neon}*/calligra/krita':
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: krita/3.1

# Apps

'*{anonscm.debian,anongit.neon}*/applications/*':
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: Applications/16.12

# Neon-packaging

'*anongit.neon*/neon-packaging/kphotoalbum':
  'Neon/stable':
    upstream_scm:
      branch: 5.x

'*anongit.neon*/neon-packaging/calamares':
  'Neon/unstable':
    upstream_scm:
      type: git
      url: https://github.com/calamares/calamares.git
      branch: master

'*anongit.neon*/neon-packaging/kdesdk-devenv-dependencies':
  '*':
    upstream_scm:
      type: git
      branch: 2.4.x-stable
      url: git://anongit.kde.org/kdesdk-devenv-dependencies.git

'*anongit.neon*/neon-packaging/qoauth':
  '*':
    upstream_scm:
      url: https://github.com/ayoy/qoauth.git

# Extras

'*{anonscm.debian,anongit.neon}*/*/{kdeconnect,kdeconnect-plasma}':
  '*':
    upstream_scm:
      url: git://anongit.kde.org/kdeconnect-kde.git
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: 1.x

'*{anonscm.debian,anongit.neon}*/*/libkgapi':
  '{kubuntu_stable,Neon/stable,Neon/release}':
    upstream_scm:
      branch: LibKGAPI/5.3

'*{anonscm.debian,anongit.neon}*/applications/ktp-common-internals':
  kubuntu_unstable:
    upstream_scm:
      branch: mklapetek/SpaceBar

# STD

'*anongit.neon*/kde-std/kdevelop':
  '{Neon/stable,Neon/release}':
    upstream_scm:
      branch: 5.1

'*anongit.neon*/kde-std/kdevplatform':
  '{Neon/stable,Neon/release}':
    upstream_scm:
      branch: 5.1

'*anongit.neon*/kde-std/kdevelop-pg-qt':
  '{Neon/stable,Neon/release}':
    upstream_scm:
      branch: 2.0

'*anongit.neon*/kde-std/kdevelop-python':
  '*':
    upstream_scm:
      url: git://anongit.kde.org/kdev-python.git
  '{Neon/stable,Neon/release}':
    upstream_scm:
      branch: 5.1

'*anongit.neon*/kde-std/kdevelop-php':
  '*':
    upstream_scm:
      url: git://anongit.kde.org/kdev-php.git
  '{Neon/stable,Neon/release}':
    upstream_scm:
      branch: 5.1

'*anongit.neon*/kde-std/sddm':
  '{Neon/mobile}':
    upstream_scm:
      type: uscan

'*anongit.neon*/kde-std/sddm':
  '{Neon/stable}':
    upstream_scm:
      branch: master

'*anongit.neon*/kde-std/sddm':
  '{Neon/unstable}':
    upstream_scm:
      branch: develop

'*anongit.neon*/kde-std/phonon-backend-vlc':
  '*':
    upstream_scm:
      url: git://anongit.kde.org/phonon-vlc.git
  '{Neon/stable}':
    upstream_scm:
      branch: 0.9

'*anongit.neon*/kde-std/phonon-backend-gstreamer':
  '*':
    upstream_scm:
      url: git://anongit.kde.org/phonon-gstreamer.git
  '{Neon/stable}':
    upstream_scm:
      branch: 4.9

# Other stuff

'*anongit.neon*/kde-req/phonon':
  '{Neon/stable}':
    upstream_scm:
      branch: 4.9

## Qt

'*{anonscm.debian,anongit.neon,gitlab.com}*/{qt,netrunner-debian-qt}/*':
  kubuntu_unstable:
    upstream_scm:
      url: http://code.qt.io/git/qt/<%= name %>.git
      branch: 5.4
  Neon/release:
    upstream_scm:
      type: uscan
  Neon/testing:
    upstream_scm:
      type: uscan
  Netrunner/stable:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/q/<%= name %>-opensource-src/<%= name %>-opensource-src_5.5.1.orig.tar.xz

'*{anonscm.debian,anongit.neon}*/qt/qt5webkit':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: http://code.qt.io/git/qt/qtwebkit.git
      branch: 5.4
  Neon/release:
    upstream_scm:
      type: uscan
  Neon/testing:
    upstream_scm:
      type: uscan

'*{anonscm.debian,anongit.neon}*/qt/qtchooser':
  Neon/release:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/q/qtchooser/qtchooser_58-gfab25f1.orig.tar.xz

'*{anonscm.debian,anongit.neon}*/qt/qtpim':
  Neon/mobile:
    upstream_scm:
      type: tarball
      url: http://archive.ubuntu.com/ubuntu/pool/main/q/qtpim-opensource-src/qtpim-opensource-src_5.0~git20140515~29475884.orig.tar.gz

### Bindings

'*anongit.neon*/forks/sip4':
  Neon/release:
    upstream_scm:
      type: uscan
  master:
    upstream_scm:
      type: uscan

'*anongit.neon*/forks/pyqt5':
  Neon/release:
    upstream_scm:
      type: uscan
  master:
    upstream_scm:
      type: uscan

## Misc

'*anongit.neon*/forks/*':
  master:
    upstream_scm:
      type: uscan
  debian-unstable:
    upstream_scm:
      type: uscan

'*anongit.neon*/forks/gpgme':
  'Neon/{stable,unstable}':
    upstream_scm:
      type: uscan

'*anongit.neon*/forks/drumstick':
  master:
    upstream_scm:
      type: tarball
      url: http://sourceforge.mirrorservice.org/d/dr/drumstick/1.1.0/drumstick-1.1.0.tar.bz2

'*anongit.neon*/forks/libxkbcommon':
  '*':
    upstream_scm:
      type: uscan

'*{anonscm.debian,anongit.neon}*/frameworks/prison':
  'Neon/{release}':
    upstream_scm:
      type: tarball
      url: http://weegie.edinburghlinux.co.uk/~tittiatcoke/prison-kf5_5.25~git20161107.orig.tar.gz

'*{anonscm.debian,anongit.neon}*/frameworks/purpose':
  'Neon/stable':
    upstream_scm:
      branch: master

'*{anonscm.debian,anongit.neon}*/kde-extras/debconf-kde':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/libdebconf-kde.git

'*{anonscm.debian,anongit.neon}*/kde-extras/kdeconnect-plasma':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/kdeconnect-kde.git

'*{anonscm.debian,anongit.neon}*/kde-extras/qapt':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/libqapt.git

'*{anonscm.debian,anongit.neon}*/kde-req/qca-qt5':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/qca.git

'*{anonscm.debian,anongit.neon}*/kde-std/sddm':
  '{kubuntu_unstable,Neon/stable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/sddm/sddm.git

'*{anonscm.debian,anongit.neon}*/kde-extras/qt-gstreamer':
  '*':
    upstream_scm:
      url: git://anongit.freedesktop.org/gstreamer/qt-gstreamer

'*{anonscm.debian,anongit.neon}*/kde-extras/telepathy-accounts-signon':
  '*':
    upstream_scm:
      url: https://gitlab.com/accounts-sso/telepathy-accounts-signon.git

'*{anonscm.debian,anongit.neon}*/kde-extras/libaccounts-glib':
  '*':
    upstream_scm:
      url: https://gitlab.com/accounts-sso/libaccounts-glib.git

'*{anonscm.debian,anongit.neon}*/kde-extras/konversation':
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: 1.6

'*{anonscm.debian,anongit.neon}*/kde-extras/kirigami':
  '{kubuntu_stable,Neon/stable,Neon/unstable}':
    upstream_scm:
      branch: Kirigami/1.1

'*anongit.neon*/kde-extras/kirigami2':
  '{Neon/stable,Neon/unstable}':
    upstream_scm:
      type: git
      url: git://anongit.kde.org/kirigami.git
      branch: master

'*{anonscm.debian,anongit.neon}*/kde-extras/peruse':
  '{Neon/stable}':
    upstream_scm:
      branch: master

'*{anonscm.debian,anongit.neon}*/kde-extras/massif-visualizer':
  'Neon/stable':
    upstream_scm:
      branch: 0.6

'*{anonscm.debian,anongit.neon}*/forks/libkolab':
  'Neon/unstable':
    upstream_scm:
      url: https://git.kolab.org/diffusion/LK/libkolab.git
      branch: libkolab-1.0 # tittiatcoke says this is the correct Qt5 branch!
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      url: https://git.kolab.org/diffusion/LK/libkolab.git
      branch: libkolab-1.0

'*{anonscm.debian,anongit.neon}*/forks/libkolabxml':
  'Neon/unstable':
    upstream_scm:
      url: https://git.kolab.org/diffusion/LKX/libkolabxml.git
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      url: https://git.kolab.org/diffusion/LKX/libkolabxml.git
      branch: libkolabxml-1.1

'*anongit.neon*/forks/libarchive':
  '{Neon/release-lts,Neon/release,Neon/stable,Neon/unstable}':
    upstream_scm:
      type: uscan

'*anongit.neon*/forks/gcompris':
  'Neon/stable':
    upstream_scm:
      branch: KDE/0.60

'*anongit.neon*/forks/qt5keychain':
  '{Neon/release,Neon/stable,Neon/unstable}':
    upstream_scm:
      type: uscan

'*anongit.neon*/forks/ldc':
  'Neon/release':
    upstream_scm:
      type: tarball
      url: https://launchpad.net/~ximion/+archive/ubuntu/tests/+files/ldc_1.1.0+b3.orig.tar.gz

'*anongit.neon*/forks/meson':
  'Neon/release':
    upstream_scm:
      type: tarball
      url: https://launchpad.net/~ximion/+archive/ubuntu/tests/+files/meson_0.35.0.orig.tar.gz

'*anongit.neon*/forks/lmdb':
  'Neon/release':
    upstream_scm:
      type: tarball
      url: https://launchpad.net/~ximion/+archive/ubuntu/tests/+files/lmdb_0.9.18.orig.tar.gz


'*anongit.neon*/forks/mustache-d':
  'Neon/release':
    upstream_scm:
      type: tarball
      url: https://launchpad.net/~ximion/+archive/ubuntu/tests/+files/mustache-d_0.1.1.orig.tar.gz

'*anongit.neon*/forks/ninja-build':
  'Neon/release':
    upstream_scm:
      type: tarball
      url: https://launchpad.net/~ximion/+archive/ubuntu/tests/+files/ninja-build_1.7.1.orig.tar.gz

'*anongit.neon*/forks/avogadro':
  'Neon/unstable':
    upstream_scm:
      type: uscan

'*anonscm.debian*/krap/libindi':
  'master':
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/libi/libindi/libindi_1.2.0.orig.tar.gz

'*anonscm.debian*/krap/libnova':
  'master':
    upstream_scm:
      type: tarball
      url: http://mirrors.accretive-networks.net/debian/pool/main/libn/libnova/libnova_0.16.orig.tar.xz

'*anonscm.debian*/krap/grantlee':
  'master':
    upstream_scm:
      type: tarball
      url: http://mirror.sucs.swan.ac.uk/pub/linux/debian/pool/main/g/grantlee5/grantlee5_5.1.0.orig.tar.gz

## Mobile

### Xorg
'*{anonscm.debian,anongit.neon}*/xserver/xorg-server':
  debian-experimental:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/x/xorg-server/xorg-server_1.18.0.orig.tar.gz

'*{anonscm.debian,anongit.neon}*/proto/x11proto-core':
  debian-unstable:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/x/x11proto-core/x11proto-core_7.0.28.orig.tar.gz

'*{anonscm.debian,anongit.neon}*/proto/x11proto-randr':
  debian-unstable:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/x/x11proto-randr/x11proto-randr_1.5.0.orig.tar.gz

https://github.com/plasma-phone-packaging/simplelogin-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/scratch/davidedmundson/simplelogin.git
https://github.com/plasma-phone-packaging/qtvirtualkeyboard:
  Neon/mobile:
    upstream_scm:
      type: uscan
https://github.com/plasma-phone-packaging/plasma-phone-settings-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-phone-settings.git
https://github.com/plasma-phone-packaging/plasma-camera-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-camera
https://github.com/plasma-phone-packaging/plasma-phone-components-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-phone-components.git
https://github.com/plasma-phone-packaging/plasma-mobile-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-mobile
https://github.com/plasma-phone-packaging/plasma-settings-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-settings
https://github.com/plasma-phone-packaging/plasma-maliit-plugins-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-maliit-plugins.git
https://github.com/plasma-phone-packaging/plasma-samegame-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-samegame
https://github.com/plasma-phone-packaging/mtp-server:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/mtp-server.git
https://github.com/plasma-phone-packaging/okular:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/okular
    upstream_scm:
      branch: frameworks

https://github.com/plasma-phone-packaging/plasma-maliit-framework-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-maliit-framework.git
https://github.com/plasma-phone-packaging/libepoxy:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/anholt/libepoxy.git

https://github.com/plasma-phone-packaging/appstream:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/ximion/appstream.git

https://github.com/plasma-phone-packaging/screenshotapp:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/plasma-apps/screenshotapp.git

https://github.com/plasma-phone-packaging/inputcontext-gtk:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/maliit/inputcontext-gtk.git
      branch: tags/0.99.0

https://github.com/plasma-phone-packaging/libhybris:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/libhybris/libhybris.git

https://github.com/plasma-phone-packaging/videoPlayer-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/plasma-apps/videoPlayer.git
      branch: plasma

https://github.com/debian-packaging/mintupdate:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/blueshell-next/mintupdate

https://github.com/debian-packaging/*mint*:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/linuxmint/<%= name %>

https://github.com/*/*calamares*:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/calamares/calamares
  'master':
    upstream_scm:
      type: uscan

https://github.com/netrunner-odroid/xserver-xorg-video-mali:
  '*':
    upstream_scm:
      url: https://github.com/mdrjr/c1_mali_ddx

https://github.com/netrunner-odroid/mali-x11:
  '*':
    upstream_scm:
      url: https://github.com/mdrjr/c1_mali_libs

https://github.com/netrunner-odroid/c2-mali-x11:
  '*':
    upstream_scm:
      url: https://github.com/mdrjr/c2_mali

https://github.com/netrunner-odroid/xserver-xorg-video-mali-450:
  '*':
    upstream_scm:
      url: https://github.com/mdrjr/c2_mali_ddx

https://github.com/rpi2-stuff/mesa:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.freedesktop.org/mesa/mesa
      branch: 11.1

'https://github.com/ds9-extras-packaging/*':
  '*':
    upstream_scm:
      url: https://github.com/ds9-extras/<%= name %>

https://github.com/ds9-extras-packaging/groupingplasmoid:
  '*':
    upstream_scm:
      url: git://anongit.kde.org/scratch/davidedmundson/groupingplasmoid.git
      type: git

'https://github.com/ds9-extras-packaging/{krita,qtcharts-opensource-src}':
  '*':
    upstream_scm:
      type: uscan

https://github.com/ds9-extras-packaging/skype:
  '*':
    upstream_scm:

https://github.com/ds9-extras-packaging/steam:
  '*':
    upstream_scm:
      type: uscan

https://github.com/ds9-extras-packaging/samba-mounter:
  '*':
    upstream_scm:
      url: git://anongit.kde.org/samba-mounter.git
      branch: master

'https://github.com/ds9-extras-packaging/{plasma,kcm,ice}-*':
  '*':
    upstream_scm:
      url: https://github.com/plasma-extensions/<%= name %>

'https://github.com/ds9-extras-packaging/kcm-{plasma-services,about-extended}':
  '*':
    upstream_scm:
      url: https://github.com/ds9-extras/<%= name %>

https://github.com/ds9-extras-packaging/imagewriter:
  '*':
    upstream_scm:
      url: https://github.com/openSUSE/imagewriter

https://github.com/ds9-extras-packaging/ksuperkey:
  '*':
    upstream_scm:
      url: https://github.com/hanschen/ksuperkey.git

https://github.com/ds9-extras-packaging/{xdgurl,telepathy-,telegram-}*:
  '*':
    upstream_scm:
      type: uscan

https://github.com/ds9-extras-packaging/simplemenu:
  '*':
    upstream_scm:
      url: git://anongit.kde.org/scratch/hein/simplemenu.git
      branch: 5.8

https://github.com/ds9-extras-packaging/kcm-kernel-config:
  '*':
    upstream_scm:
      url: https://github.com/plasma-extensions/kernel-kcm

https://github.com/plasmazilla/mozilla-kde-support:
  'master':
    upstream_scm:
      url: https://github.com/openSUSE/kmozillahelper

https://github.com/plasmazilla/firefox:
  'release/kde':
    upstream_scm:
      type: firefox
      url: http://deb.debian.org/debian/pool/main/f/firefox/firefox_50.1.0.orig.tar.xz

'https://github.com/ds9-debian-frameworks/*':
  'Neon/release':
    upstream_scm:
      type: uscan

https://github.com/ds9-common/sortinglaunchers:
  'master':
    upstream_scm:
      type: git
      url: git://anongit.kde.org/scratch/hein/sortinglaunchers.git

https://github.com/ds9-common/anttoolbar:
  'master':
    upstream_scm:
      type: uscan

'https://github.com/ds9-debian-packaging-backports/*':
  '*':
    upstream_scm:
      type: uscan

'*anonscm.debian.org/pkg-xorg/lib/libxkbcommon':
  '*':
    upstream_scm:
      type: tarball
      url: http://xkbcommon.org/download/libxkbcommon-0.6.1.tar.xz

https://github.com/netrunner-odroid/*-uboot:
  '*':
    upstream_scm:
      type: git
      url: https://github.com/mdrjr/<%= name %>

https://github.com/netrunner-odroid/c1-bootini:
  '*':
    upstream_scm:
      type: git
      url: https://github.com/mdrjr/c1_bootini

https://github.com/netrunner-odroid/c1-linux:
  '*':
    upstream_scm:
      type: git
      url: https://github.com/hardkernel/linux
      branch: odroidc-3.10.y

https://github.com/netrunner-odroid/c2-linux:
  '*':
    upstream_scm:
      type: git
      url: https://github.com/hardkernel/linux
      branch: odroidc2-3.14.y


https://github.com/shadeslayer/kde-l10n-common:
  '*':
    upstream_scm:
      type: kde-l10n

'*{anonscm.debian,anongit.neon}*/pkg-virtualbox/virtualbox*':
  '*':
    upstream_scm:
      type: tarball
      url: 'http://deb.debian.org/debian/pool/contrib/v/virtualbox/virtualbox_5.1.10-dfsg.orig.tar.xz'
