# UScan releases

'*anongit.neon*':
  'Neon/release':
    upstream_scm:
      type: uscan

# Plasma

'*{debian.org,anongit.neon}*/plasma/*':
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: Plasma/5.8

'*{debian.org,anongit.neon}*/plasma/plasma-discover':
  '*':
    upstream_scm:
      url: git://anongit.kde.org/discover.git

'*{debian.org,anongit.neon}*/plasma/plasma-mediacenter':
  '*':
    upstream_scm:
      branch: Plasma/5.7

# Apps

'*{debian.org,anongit.neon}*/applications/*':
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: Applications/16.08

# Extras

'*{debian.org,anongit.neon}*/*/{kdeconnect,kdeconnect-plasma}':
  '*':
    upstream_scm:
      url: git://anongit.kde.org/kdeconnect-kde.git
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: 0.9

'*{debian.org,anongit.neon}*/*/libkgapi':
  '{kubuntu_stable,Neon/stable,Neon/release}':
    upstream_scm:
      branch: LibKGAPI/5.3

'*{debian.org,anongit.neon}*/applications/ktp-common-internals':
  kubuntu_unstable:
    upstream_scm:
      branch: mklapetek/SpaceBar

# STD

'*anongit.neon*/kde-std/kdevelop':
  '{Neon/stable,Neon/release}':
    upstream_scm:
      branch: 5.0

'*anongit.neon*/kde-std/kdevplatform':
  '{Neon/stable,Neon/release}':
    upstream_scm:
      branch: 5.0

'*anongit.neon*/kde-std/kdevelop-pg-qt':
  '{Neon/stable,Neon/release}':
    upstream_scm:
      branch: 5.0

'*anongit.neon*/kde-std/sddm':
  '{Neon/mobile}':
    upstream_scm:
      type: uscan

# Other stuff

## Qt

'*{debian.org,anongit.neon,gitlab.com}*/{qt,netrunner-debian-qt}/*':
  kubuntu_unstable:
    upstream_scm:
      url: http://code.qt.io/git/qt/<%= name %>.git
      branch: 5.4
  Neon/release:
    upstream_scm:
      type: uscan
  Netrunner/stable:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/q/<%= name %>-opensource-src/<%= name %>-opensource-src_5.5.1.orig.tar.xz

'*{debian.org,anongit.neon}*/qt/qt5webkit':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: http://code.qt.io/git/qt/qtwebkit.git
      branch: 5.4
  Neon/release:
    upstream_scm:
      url: http://http.debian.net/debian/pool/main/q/qtwebkit-opensource-src/qtwebkit-opensource-src_5.6.0+dfsg.orig.tar.xz

'*{debian.org,anongit.neon}*/qt/qtchooser':
  Neon/release:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/q/qtchooser/qtchooser_58-gfab25f1.orig.tar.xz

'*{debian.org,anongit.neon}*/qt/qtpim':
  Neon/mobile:
    upstream_scm:
      type: tarball
      url: http://archive.ubuntu.com/ubuntu/pool/main/q/qtpim-opensource-src/qtpim-opensource-src_5.0~git20140515~29475884.orig.tar.gz

### Bindings

'*anongit.neon*/forks/pyqt5':
  Neon/release:
    upstream_scm:
      type: tarball
      url: http://archive.ubuntu.com/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/pool/universe/p/pyqt5/pyqt5_5.5.1+dfsg.orig.tar.gz
  master:
    upstream_scm:
      type: tarball
      url: http://archive.ubuntu.com/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/ubuntu/pool/universe/p/pyqt5/pyqt5_5.5.1+dfsg.orig.tar.gz

## Misc

'*anongit.neon*/forks/*':
  master:
    upstream_scm:
      type: uscan

'*anongit.neon*/forks/drumstick':
  master:
    upstream_scm:
      type: tarball
      url: http://sourceforge.mirrorservice.org/d/dr/drumstick/1.0.2/drumstick-1.0.2.tar.bz2

'*{debian.org,anongit.neon}*/frameworks/prison':
  'Neon/{release}':
    upstream_scm:
      type: tarball
      url: https://launchpad.net/ubuntu/+archive/primary/+files/prison-kf5_1.2~git20150223.orig.tar.gz

'*{debian.org,anongit.neon}*/kde-extras/debconf-kde':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/libdebconf-kde.git

'*{debian.org,anongit.neon}*/kde-extras/kdeconnect-plasma':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/kdeconnect-kde.git

'*{debian.org,anongit.neon}*/kde-extras/qapt':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/libqapt.git

'*{debian.org,anongit.neon}*/kde-req/qca-qt5':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/qca.git
      branch: qt5

'*{debian.org,anongit.neon}*/kde-std/sddm':
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/sddm/sddm.git

'*{debian.org,anongit.neon}*/kde-extras/qt-gstreamer':
  '*':
    upstream_scm:
      url: git://anongit.freedesktop.org/gstreamer/qt-gstreamer

'*{debian.org,anongit.neon}*/kde-extras/telepathy-accounts-signon':
  '*':
    upstream_scm:
      url: https://gitlab.com/accounts-sso/telepathy-accounts-signon.git

'*{debian.org,anongit.neon}*/kde-extras/libaccounts-glib':
  '*':
    upstream_scm:
      url: https://gitlab.com/accounts-sso/libaccounts-glib.git

'*{debian.org,anongit.neon}*/kde-extras/konversation':
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      branch: 1.6

'*{debian.org,anongit.neon}*/forks/libkolab':
  'Neon/unstable':
    upstream_scm:
      url: https://git.kolab.org/diffusion/LK/libkolab.git
      branch: libkolab-1.0 # tittiatcoke says this is the correct Qt5 branch!
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      url: https://git.kolab.org/diffusion/LK/libkolab.git
      branch: libkolab-1.0

'*{debian.org,anongit.neon}*/forks/libkolabxml':
  'Neon/unstable':
    upstream_scm:
      url: https://git.kolab.org/diffusion/LKX/libkolabxml.git
  '{kubuntu_stable,Neon/stable}':
    upstream_scm:
      url: https://git.kolab.org/diffusion/LKX/libkolabxml.git
      branch: libkolabxml-1.1

'*debian.org*/krap/libindi':
  'master':
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/libi/libindi/libindi_1.2.0.orig.tar.gz

'*debian.org*/krap/grantlee':
  'master':
    upstream_scm:
      type: tarball
      url: http://mirror.sucs.swan.ac.uk/pub/linux/debian/pool/main/g/grantlee5/grantlee5_5.1.0.orig.tar.gz

## Some Netrunner things

https://github.com/*/ksuperkey:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/hanschen/ksuperkey.git

https://github.com/*/samba-mounter:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/scratch/afiestas/samba-mounter.git
      branch: frameworks

## Mobile

### Xorg
'*{debian.org,anongit.neon}*/xserver/xorg-server':
  debian-experimental:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/x/xorg-server/xorg-server_1.18.0.orig.tar.gz

'*{debian.org,anongit.neon}*/proto/x11proto-core':
  debian-unstable:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/x/x11proto-core/x11proto-core_7.0.28.orig.tar.gz

'*{debian.org,anongit.neon}*/proto/x11proto-randr':
  debian-unstable:
    upstream_scm:
      type: tarball
      url: http://http.debian.net/debian/pool/main/x/x11proto-randr/x11proto-randr_1.5.0.orig.tar.gz

https://github.com/plasma-phone-packaging/simplelogin-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/scratch/davidedmundson/simplelogin.git
https://github.com/plasma-phone-packaging/qtvirtualkeyboard:
  Neon/mobile:
    upstream_scm:
      type: uscan
https://github.com/plasma-phone-packaging/plasma-phone-settings-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-phone-settings.git
https://github.com/plasma-phone-packaging/plasma-camera-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-camera
https://github.com/plasma-phone-packaging/plasma-phone-components-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-phone-components.git
https://github.com/plasma-phone-packaging/plasma-mobile-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-mobile
https://github.com/plasma-phone-packaging/plasma-settings-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-settings
https://github.com/plasma-phone-packaging/plasma-phone-dev-setup-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-phone-dev-setup.git
https://github.com/plasma-phone-packaging/plasma-maliit-plugins-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-maliit-plugins.git
https://github.com/plasma-phone-packaging/plasma-samegame-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-samegame
https://github.com/plasma-phone-packaging/mtp-server:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/mtp-server.git
https://github.com/plasma-phone-packaging/okular:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/okular
    upstream_scm:
      branch: frameworks

https://github.com/plasma-phone-packaging/plasma-maliit-framework-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/plasma-maliit-framework.git
https://github.com/plasma-phone-packaging/libepoxy:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/anholt/libepoxy.git

https://github.com/plasma-phone-packaging/appstream:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/ximion/appstream.git

https://github.com/plasma-phone-packaging/screenshotapp:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/plasma-apps/screenshotapp.git

https://github.com/plasma-phone-packaging/inputcontext-gtk:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/maliit/inputcontext-gtk.git
      branch: tags/0.99.0

https://github.com/plasma-phone-packaging/libhybris:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/libhybris/libhybris.git

https://github.com/plasma-phone-packaging/videoPlayer-packaging:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/plasma-apps/videoPlayer.git
      branch: plasma

https://github.com/debian-packaging/mintupdate:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/blueshell-next/mintupdate

https://github.com/debian-packaging/*mint*:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/linuxmint/<%= name %>

https://github.com/*/*calamares*:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/calamares/calamares
  'master':
    upstream_scm:
      type: uscan

https://github.com/netrunner-odroid/xserver-xorg-video-mali:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/mdrjr/c1_mali_ddx

https://github.com/netrunner-odroid/mali-x11:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: https://github.com/mdrjr/c1_mali_libs

https://github.com/rpi2-stuff/mesa:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.freedesktop.org/mesa/mesa
      branch: 11.1

https://github.com/debian-packaging/simplemenu:
  '{kubuntu_unstable,Neon/unstable}':
    upstream_scm:
      url: git://anongit.kde.org/scratch/hein/simplemenu.git

'https://github.com/ds9-extras/*':
  'master':
    upstream_scm:
      url: https://github.com/ds9-extras/<%= name %>

https://github.com/ds9-debian-packaging/imagewriter:
  'master':
    upstream_scm:
      url: https://github.com/openSUSE/imagewriter

https://github.com/ds9-debian-packaging/kcm-kernel-config:
  'master':
    upstream_scm:
      url: https://github.com/plasma-extensions/kernel-kcm

# A slightly more greedy regex in order to accomodate for tests
'*/skype':
  '*':
    upstream_scm:
